name: Rust

on:
  workflow_dispatch:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install rustfmt and clippy
      run: rustup component add rustfmt clippy

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Run shellcheck
      run: shellcheck --severity=style build.sh publish.sh publish-x86-64-Linux.sh

    - name: Run clippy checks
      run: cargo clippy --release -- -D warnings

    - name: Build and test publish script
      run: bash ./publish-x86-64-Linux.sh
